
favcolor: blue
jenkins_groupe_name_default: jenkins
jenkins_user_name_default: jenkins
jenkins_uid_default: 5500
jenkins_gid_default: 5500
jenkins_sudoers: "{{jenkins_user_name_default}} ALL=(ALL) NOPASSWD: ALL"