---
# tasks file for nex-ng
- name: new users creation {{user_name}}
  user:
    name: "{{user_name}}"
    password: "{{ user_name | password_hash('sha512') }}" 
- name: unzip
  yum:
    name: unzip
- name: create folder nexus
  file:
    path: /opt/nexus
    state: directory 
    owner: "{{user_name}}"
    group: "{{groupe_name}}"
- name: wget nexus
  get_url:
    url: https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.2-02-unix.tar.gz
    dest: /opt/nexus
    owner: "{{user_name}}"
    group: "{{groupe_name}}"
- name: Extract
  unarchive:
    remote_src: yes
    src: /opt/nexus/nexus-3.0.2-02-unix.tar.gz
    dest: /opt/nexus
    owner: "{{user_name}}"
    group: "{{groupe_name}}"
- name: copy
  copy:
    src: nexus.service
    dest: /etc/systemd/system

- name: start nexus
  systemd:
    name: nexus.service
    enabled: true
    state: started 
