- name: set sonar
  stat:
    path: /opt/sonar/sonarqube-7.6
  register: sonar_service


- debug: msg="{{sonar_service.stat.exists}}"
  when: sonar_service.stat.exists == false
  tags: never

- import_tasks: set_sonar.yml
  when: sonar_service.stat.exists == false